### ISSUE TITLE
Access to open-aiops user group and namespace 

### ISSUE THREAD

**Issue by eranra** [open-infrastructure-labs/moc-cnv-sandbox#13]
Can you add me ( eran.raichstein@gmail.com ) to `open-aiops` user-group and namespace. THX

@tumido I see the details in https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/groups/open-aiops.enc.yaml ... but I do not know the details on how to add myself there (if you can help)

@larsks @durandom @drbwa ^^^

Follow up on https://github.com/open-infrastructure-labs/moc-cnv-sandbox/issues/8

**Comment by tumido** [comment]
@eranra sure, I'll add you. Currently the resource is encrypted using our OperateFirst GPG master key, that's why you can't do anything about it. If you have a team GPG key, we can add it to our sops keyring as well, so you can manage the encrypted resources which belong to your team on your own as well. See our (unfinished) docs for more detail. It'll be finalized in a bit: https://github.com/operate-first/support/pull/40

**Comment by tumido** [comment]
PR pending: https://github.com/operate-first/apps/pull/124

**Comment by eranra** [comment]
@tumido thanks for the super-quick reply ... appreciated :-) 

Using your `master key` is good for now.

**Comment by HumairAK** [comment]
Looks like this was resolved, closing -- feel free to re-open if needed.
