### ISSUE TITLE
Access to MOC CNV Cluster

### ISSUE THREAD

**Issue by drbwa** [open-infrastructure-labs/moc-cnv-sandbox#8]
Hi. Can you please provide access to MOC to the members of the [Open AIOps](https://github.com/Open-AIOps) project?

* davidoha _at_ gmail _dot_ com
* ronen _dot_ schaffer _at_ gmail _dot_ com
* shahla _dot_ robert _at_ gmail _dot_ com
* bruno _dot_ wassermann _at_ gmail _dot_ com

**Comment by eranra** [comment]
@larsks @durandom ^^^

**Comment by durandom** [comment]
@larsks let's use this to flesh out https://github.com/open-infrastructure-labs/ops-issues/issues/1 
@HumairAK can you point @drbwa to our current doc on onboarding new projects

**Comment by tumido** [comment]
PR pending https://github.com/operate-first/apps/pull/104

**Comment by tumido** [comment]
Ticket resolved :tada:

Sorry for the delay, we're still ironing out the process.

We've created for you:
- a namespace [`open-aiops`](https://console-openshift-console.apps.cnv.massopen.cloud/k8s/cluster/projects/open-aiops) to begin with (you can request additional ones via issue in [`operate-first/support`, using the "Onboard to a cluster" template](https://github.com/operate-first/support/issues/new/choose) or here in this ticket or via PR [here](https://github.com/operate-first/apps/tree/master/cluster-scope/base/namespaces))
- a user group `open-aiops` including you for now (additional users can be requested in [`operate-first/support`, using the "Onboard to a cluster" template](https://github.com/operate-first/support/issues/new/choose), or here in this ticket or added via PR [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/groups/open-aiops.enc.yaml))

To access the cluster, please follow [this documentation](https://www.operate-first.cloud/operators/moc-cnv-sandbox/docs/about-the-cluster.md)

If you'd like to onboard the Argo CD feel free create an issue at [`operate-first/support`, using the "Onboard to Onboard to Continuous Deployment" template](https://github.com/operate-first/support/issues/new/choose) or follow the docs linked in that template if you want to implement that yourself.

**Comment by tumido** [comment]
@larsks this ticket can be closed now, please. :slightly_smiling_face:

**Comment by drbwa** [comment]
Thank you @tumido . I tried to look into how to add users via the link you have shared <https://github.com/operate-first/apps/blob/master/namespaces/overlays/moc/open-aiops/group.enc.yaml>, but am getting an HTTP 404. Poked around the repo a bit, but did not find what I was looking for. Could you please point me at an example of the files I would need to modify?

**Comment by tumido** [comment]
@drbwa sorry for that, we moved the folder because we agreed (and finally settled) on a different format. See [ADR 0009](https://github.com/operate-first/blueprint/blob/main/docs/adr/0009-cluster-resources.md).

The files you're looking for are located at:

https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/groups/open-aiops.enc.yaml

If you want to modify that file, we'd need to re-encrypt it with multiple GPG keys so we both maintain access to it. Please read this doc:

https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md#adding-users

I'll update my previous comment to fully reflect what changed so all the links are accessible to you again. :)

**Comment by drbwa** [comment]
@tumido I think we are fine for now in terms of users. Just so that I understand and have this for reference, could you please explain the business with the keys for dummies? I guess we would need to add a key for our project/team, but what would the mechanics of enabling us to add/manage users look like more end-to-end?

**Comment by tumido** [comment]
For a general secrets management in your applications we've compiled this doc:
https://github.com/operate-first/support/blob/main/docs/secret_management.md

There you can learn about "how" we approach the secret management in general. And how you can apply this to your application manifests so it can be auto deployed via ArgoCD.

When it comes to the cluster resources, all of this would be a bit different. That's because we already onboarded your team and user group, using our GPG key only. If you want to obtain access to the group resource (decrypt and change), we have to add your GPG key to this resource and reencrypt it using both of the keys (your key and ours).

Please tell us where we can get your GPG key (attach pubkey in here or point to a keyserver). I'll then reencrypt the `Group|open-aiops` resource using both keys and commit it to this repo. Once that is done, you will be able to edit the resource using sops, as described in the doc above (note: you'd need to fetch our GPG pubkey for successful reencryption).

They you can simply commit this updated file and open it as a PR against the `operate-first/apps` repo. I hope it make a bit more sense now. Let me know, how we can improve this whole process. :slightly_smiling_face:

**Comment by tumido** [comment]
Btw, as @HumairAK  pointed out to me right now:

Of course you can also manage the users separately from our `cluster-scope` ArgoCD managed group You can just deploy a `RoleBinding` on your own, specifying additional users as the subjects.

That being said, the `cluster-scope` ArgoCD application (managed by us) is meant to auto-create namespaces and bootstrap them with project admins in case of a cluster disaster. It is highly recommended that the users responsible for managing the namespaces (or most active admins in the namespace) are added within our `cluster-scope` application.
